/**
 * GracelineCMS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Organization } from './organization';


export interface ContentModule { 
    id?: string;
    name: string;
    description: string;
    createdAt?: string;
    organization: Organization;
}

