/**
 * GracelineCMS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { ContentModule } from './contentModule';


export interface Organization { 
    id?: string;
    name: string;
    users?: Array<User>;
    contentModules?: Array<ContentModule>;
}

