/**
 * GracelineCMS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface RefreshToken { 
    id?: string;
    refreshTokenValue: string;
    createdAt?: string;
    expiresAt?: string;
    user: User;
}

