/**
 * GracelineCMS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Organization } from './organization';
import { RefreshToken } from './refreshToken';
import { AuthCode } from './authCode';


export interface User { 
    id?: string;
    emailAddress: string;
    refreshTokens?: Array<RefreshToken>;
    authCodes?: Array<AuthCode>;
    organizations?: Array<Organization>;
}

